// User Types
export const UPDATE_PLAYER = 'UPDATE_PLAYER'
export const CREATE_PLAYER = 'CREATE_PLAYER'
export const GET_PLAYERS = 'GET_PLAYERS'
export const MODAL_DISPLAYED = 'MODAL_DISPLAYED'
export const MODAL_DISPLAYED_UPDATE = 'MODAL_DISPLAYED_UPDATE'
export const REFRESH_LIST = 'REFRESH_LIST'

